### ISSUE TITLE
исправить AuthOptions

### ISSUE THREAD

**Issue by Nemo-Illusionist** [Poostoi/Entrant#4]
- [x] вынести в appsettings.*.json
- [x] должен быть в инфраструктуре
- [x] Claims должен быть ID а не login

**Comment by Poostoi** [comment]
Сделал выгрузку из appsetting. Правильно ли, то что я поля сделал static(у меня просто по другому не хотела работать)?
И я конвертирую Id в string череp Convert.ToString, нормально?

**Comment by Nemo-Illusionist** [comment]
нет, поля не должны быть статичными!
если поля статик значит где то ошибка

**Comment by Poostoi** [comment]
исправил в этом коммите ->
   refactor TokenProvider, AuthorizationModule and AuthOptions

добавил в токен провайдер, создание опции для Jwt токена, при подключении

**Comment by Poostoi** [comment]
Я пытался сделать, так чтобы она создавал экземпляр модели сам, но GetSection, Bind не хотело работать, я не знаю почему. Оно просто выдавало null
