### ISSUE TITLE
Добавить роли

### ISSUE THREAD

**Issue by Nemo-Illusionist** [Poostoi/Entrant#5]
- [x] модель с ID и Name
- [x] добавить связь [ManyToMany ](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#join-entity-type-configuration) к Account
`ToTable Package: Microsoft.EntityFrameworkCore.Relational v6.0.0`
```cs
modelBuilder
    .Entity<Post>()
    .HasMany(p => p.Tags)
    .WithMany(p => p.Posts)
    .UsingEntity(j => j.ToTable("PostTags"));
```
- [x] роль не должна иметь список акаунтов
``` cs
    .WithMany(p => null!)
```

**Comment by Poostoi** [comment]
Я не много не понял, а зачем нам добавлять связь? Или мы из  базы роль отдельно не подгружаем. а только с аккаунтом? Я добавил Роль в коммите "[Add Role](https://github.com/Poostoi/Entrant/commit/82863ea5325eed19fcda83b5c9d09c1d34b35c0e)"

**Comment by Nemo-Illusionist** [comment]
в src/Application/Enrollee.Application/Entities/User/RegistrationCommand.cs не должно быть роли
src/Application/Enrollee.Application/Entities/User/RoleCommand.cs - не нужно
src/Application/Enrollee.Application/Services/User/AddRoleService.cs - не нужно

**Comment by Poostoi** [comment]
modelBuilder
    .Entity<Post>()
    .HasMany(p => p.Tags)
    .WithMany(p => p.Posts)
    .UsingEntity(j => j.ToTable("PostTags"));

Для создание этой связи, нужно, создать свой контекст?

**Comment by Poostoi** [comment]
The expression 't => null' is not a valid member access expression. The expression should represent a simple property or field access: 't => t.MyProperty'. (Parameter 'memberAccessExpression')

```
modelBuilder.Entity<Account>()
            .HasMany(a => a.Roles)
            **_.WithMany(t => null!)_**
            .UsingEntity(acR => acR.ToTable("AccountRole"));
```
